modelRoles:
  default: ollama-cloud/glm-5.3-flash
  task: ollama-cloud/glm-5.3-flash
  commit: ollama-cloud/glm-5.3-flash
  plan: ollama-cloud/kimi-k2.6
  designer: ollama-cloud/kimi-k2.6
  vision: ollama-cloud/qwen3.5:397b
  smol: ollama-cloud/devstral-2:123b
  slow: ollama-cloud/qwen3.5:397b

github:
  enabled: true
inspect_image:
  enabled: true
